# SPDX-License-Identifier: LicenseRef-Pybind
#
# SPDX-FileCopyrightText: pybind developers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
