# SPDX-License-Identifier: LicenseRef-Pybind
#
# SPDX-FileCopyrightText: pybind developers

name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-12, windows-2019]
        python-version: ["3.9", "3.11"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify pytest

      - name: Build
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ erodius

      - name: Test
        run: pytest tests
